import {
    ShadcnLandingSVG
} from "../components/ui/icons";
import { ProjectType } from "../types";

export const ProjectList: ProjectType[] = [
  {
    icon: <ShadcnLandingSVG />,
    title: "Detection of Varicose Veins Using YOLO",
    subtitle: "AI-powered medical diagnosis",
    technologies: [],
    description: "An AI-powered system for early diagnosis and continuous monitoring of varicose veins using YOLO deep learning algorithm.",
    imgUrl: "/images/vv-detection.jpeg",
    videoUrl: "",
    githubUrl: "https://github.com/LitZeus/VV-detection",
    websiteUrl: "",
  },
  {
    icon: <ShadcnLandingSVG />,
    title: "SwipeHire: AI-Powered Job & Internship Matching App",
    subtitle: "AI-driven recruitment platform",
    technologies: [],
    description: "An AI-driven swipe-based platform connecting job seekers, interns, and recruiters for efficient matchmaking using deep learning and recommendation models.",
    imgUrl: "/images/swipehire.jpeg",
    videoUrl: "",
    githubUrl: "",
    websiteUrl: "",
  },
  {
    icon: <ShadcnLandingSVG />,
    title: "NFTix: NFT-Based Ticketing Platform",
    subtitle: "Blockchain-powered ticketing",
    technologies: [],
    description: "A blockchain-powered ticketing system using NFTs for secure, verifiable event access and collectible tickets.",
    imgUrl: "/images/nftix.jpeg",
    videoUrl: "",
    githubUrl: "https://github.com/LitZeus/NFTix",
    websiteUrl: "",
  },
  {
    icon: <ShadcnLandingSVG />,
    title: "CineSenseAI: AI-Based Movie Recommendation System",
    subtitle: "AI-driven movie recommendations",
    technologies: [],
    description: "An AI-powered movie recommendation system using NLP, cosine similarity, and sentiment analysis to enhance user experience.",
    imgUrl: "/images/cinesenseai.jpeg",
    videoUrl: "",
    githubUrl: "https://github.com/LitZeus/CineSenseAI",
    websiteUrl: "",
  },
  {
    icon: <ShadcnLandingSVG />,
    title: "TabIt: Web Extension for Tab Management",
    subtitle: "Productivity browser extension",
    technologies: [],
    description: "A browser extension to save, organize, and manage open tabs into named groups for better productivity.",
    imgUrl: "/images/tabit-ss.png",
    videoUrl: "",
    githubUrl: "https://github.com/LitZeus/TabIt",
    websiteUrl: "",
  },
  {
    icon: <ShadcnLandingSVG />,
    title: "ChatDocs AI: RAG-Based AI PDF Assistant",
    subtitle: "Generative AI document assistant",
    technologies: [],
    description: "A generative AI-powered tool for interactive communication with PDF documents using Retrieval-Augmented Generation (RAG).",
    imgUrl: "/images/chatdocsai.jpeg",
    videoUrl: "",
    githubUrl: "https://github.com/LitZeus/ChatDocs-AI",
    websiteUrl: "",
  },
  {
    icon: <ShadcnLandingSVG />,
    title: "VidForensicsTool: AI-Based Video Forensic Analysis",
    subtitle: "AI-driven video authentication",
    technologies: [],
    description: "A digital forensic tool for detecting video tampering, deepfakes, and verifying authenticity using metadata analysis and frame inspection.",
    imgUrl: "/images/vidforensics.jpeg",
    videoUrl: "",
    githubUrl: "https://github.com/LitZeus/VidForensicsTool",
    websiteUrl: "",
  },
];
